name: Docker Image CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: ./deploy.sh

    - name: Test du serveur web
      run: |
        sudo lsof -i:4555
        if [ $? -eq 0 ]; then
          echo "Server Web Running"
        else
          echo "Server Web Not Runing" 
          exit 1
        fi
    
    - name: Envoie du Challenge Webhook
      run: |
        response=$(curl -X GET "http://127.0.0.1:4555/?hub.verify_token=AMPALIBE&hub.challenge=CHALLENGE_ACCEPTED&hub.mode=subscribe")
        if [ $response = "CHALLENGE_ACCEPTED" ]; then
          echo "OK! : $response"
        else
          echo KO!
          exit 1
        fi

    - name: "Test du reception de l'Applicatif"
      run: |
        response=$(curl -H "Content-Type: application/json" -X POST "http://127.0.0.1:4555/?testmode=1" -d '{"object": "page", "entry": [{"messaging": [ {"sender": {"id": "test_user"}, "message": {"text":"TEST_MESSAGE"}}]}]}')
        if [ $response = '{"status":"ok"}' ]; then
          echo "Reception de l'Applicatif fonctionnelle!"
        else
          echo KO!
          exit 1
        fi
